<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-R71D8IR" failures="0" tests="13" name="com.qa.opencart.tests.LoginPageTest" time="188.848" errors="1" timestamp="2025-06-02T10:43:55 EDT" skipped="4">
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageURLTest" time="0.043"/>
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="forgotPasswordLinkExistTest" time="0.814"/>
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageTitleTest" time="0.000">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="forgotPasswordLinkExistTest" time="0.002">
    <skipped/>
  </testcase> <!-- forgotPasswordLinkExistTest -->
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="setup" time="180.701">
    <error message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: &#039;DESKTOP-R71D8IR&#039;, ip: &#039;192.168.2.10&#039;" type="org.openqa.selenium.SessionNotCreatedException">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-R71D8IR', ip: '192.168.2.10'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:152)
at com.qa.opencart.factory.DriverFactory.initRemoteDriver(DriverFactory.java:102)
at com.qa.opencart.factory.DriverFactory.initDriver(DriverFactory.java:63)
at com.qa.opencart.base.BaseTest.setup(BaseTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.beforeRun(TestRunner.java:633)
at org.testng.TestRunner.run(TestRunner.java:595)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:424)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:187)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:53)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
... 22 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2964)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
... 3 more
]]>
    </error>
  </testcase> <!-- setup -->
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="forgotPasswordLinkExistTest" time="0.756"/>
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageTitleTest" time="0.052"/>
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageTitleTest" time="0.030"/>
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageURLTest" time="0.000">
    <skipped/>
  </testcase> <!-- loginPageURLTest -->
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageURLTest" time="0.026"/>
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="doLoginTest" time="3.450"/>
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="doLoginTest" time="2.974"/>
  <system-out/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="doLoginTest" time="0.000">
    <skipped/>
  </testcase> <!-- doLoginTest -->
  <system-out/>
</testsuite> <!-- com.qa.opencart.tests.LoginPageTest -->
